dist: trusty
sudo: required
language: java
jdk:
- openjdk8
- oraclejdk8
before_install:
- sudo apt-get update
- sudo apt-get install -y texlive texlive-base texlive-latex-extra texlive-fonts-extra
  python-virtualenv librsvg2-bin
- wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-linux.tar.gz
- tar -xzvf pandoc-2.5-linux.tar.gz
- rm pandoc-2.5-linux.tar.gz
- sudo mv pandoc-2.5 /opt
- sudo chmod +x /opt/pandoc-2.5/bin/pandoc
- sudo ln -s /opt/pandoc-2.5/bin/pandoc /usr/local/bin/pandoc
- sudo ln -s /opt/pandoc-2.5/bin/pandoc-citeproc /usr/local/bin/pandoc-citeproc
script:
- cd spec-publisher
- mvn clean package
- java -jar target/mets-profile-proc.jar ../profile/E-ARK-DIP.xml
- cd ..
- bash create-site.sh
- bundle install
- bundle exec jekyll build -s ./docs -d ./_site
- bundle exec htmlproofer ./_site --file-ignore /javadoc/ --only-4xx --check-html
- cd spec-publisher
- git checkout feat/pdf-publication
- mvn clean package
- java -jar target/mets-profile-proc.jar ../profile/E-ARK-DIP.xml
- cd ..
- bash create-pdf.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  local_dir: docs
  fqdn: earkdip.dilcis.eu
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: OT1rmJ/+ywbA88+8PwAojxy3uvzUk07hdHVTYPgYIFnTC0KBKSjrZZkJ+cwX9xtqRmVDGCGyl+x3WYy02tS9jubC9zWkArxJl1lT9AvXFn4tXzDoF1lRjp2Bgk6uEmk8BZbERs6Ef7C3aFj+qwuoioPEhCQosxTrEqt7gVuAyASsFm+7q1HJqKWwAV6hPAEHVsrNFaQGg84XO+TMT3l3UlXetGD9IhZsbo+HGHqp0F2zlUSVaGfEHC5MJPHWO9QQRVoPY2ZT8okhL/zAxivhwnn3qFdQwVObBFs4Q5q0gBkg/ahQ4hMFISfTqvxlL52C7JTCFWxX2apZwUIL5FQ3PIsr5JUn3yPvZTXzOPDGkzHZmIWPeMdzB5HcJEl73WOyQ7z08hGiwTw46BDWlZUQ8JwFEquNadKvX3iJA5u/TGQ17uB2h3ZZlb/0RtBxPuK59RBwBKtt5jgHq+RBH6o+Z6KPt/zyKDbFt9m6SC/FBdvLSk3paMke5mdONDPro02Yl0i5bk+0XPYhm5Ci5IMU8vfWPEn5SgRcprQ9dBM7NOwAi0retvj4FxCPbIZRxaTxuYbvZdJ4ZTnw/mT8oMBsrAnM6cu+sF4a4szjNjLvjsOs+NReFXBz6qvSLUn6PWfTsRwmNK8/RK3W0PUi18oRY/masUo+Mp/r2RsQlNuslsI=
  - secure: E8DPoNhxnPHNIlBn5HiBb/D+LGyNETZjgMgS2Dyb26y8DSdQTnSexj0uFfLWDPeD6T6v0UEO+WOhChkCXdR/lOb6IjVuRtB0YTq/WJfROqtI3rtDQXoHKR+SeVsOZYoTDGfLZTdSrSPHH2+/Gk7H+3m00QmrIInHISQySKltlY5bge1udtcAFxoBkFX4iMslFC4a9GS1Hac6ZoiEBbCVwj+2qn9cz263hocMZfHsqXTMxbzWYIg02vgGrL3lZXLqsOcbkrRjxJevYfB1FPLxLU6jCwdII8VxfwMVoQBvS+NvvrMMydTLCEEEEJknpGxV9fE6ncZOLZ99xYqxmPzLtQ3ztvSN4ACavrzrsGeI5Vc0t5wX0IZ6CadSyXw9A47icWMdY/psH5og2GsV51XUx4iPB+VS3TxB8VyVvcVoHLH8xPYlntny+ZlqAGQPsuimfO76FpWse4EVA9+Eu/1VbiTGkbByNMUXNXcP6e6IxqbWk7rRRbvVYwxw6RUD7JP4f6z6MmgUyhvyN+W3wvt+8sxfbH9VFbGDQN+zHVarsRn3FAT/v5hUS1zFgO1J5q0g3PJEPxtvPvMOG+Mm3DpbWRVfR4ELn+FbXPhgk54gRJ/uM1n9/ZrJXgaHgSlV9jMaHiZPP1MNmDqewG8PCUjI4jXHZ2T0QGFjF5t5lml3Y/s=
